#!/bin/sh

if [ -z $(git config user.name) -o -z $(git config user.email) ] ; then

	echo 'git config user.name or git config user.email is not setted.'

	if [ -z $(git config user.name) ] ; then
		git config --local user.name "$GIT_USER" \
			&& \
		echo "git config --local user.name ${GIT_USER}"
	fi

	if [ -z $(git config user.email) ] ; then
		git config --local user.email "$GIT_EMAIL" \
			&& \
		echo "git config --local user.email ${GIT_EMAIL}"
	fi

	echo 'Please re-commit'
  exit 1
fi
